import pyautogui
import time 

pyautogui.hotkey("win", "P", interval=0.25)
pyautogui.press("Home")
pyautogui.press("enter", interval=1.25)


pyautogui.hotkey("win", interval=0.25)
pyautogui.write("chrome", interval=0.25)
pyautogui.press("enter", interval=1.25)
pyautogui.click(x= 300, y  = 500)
pyautogui.press("tab")
pyautogui.press("enter", interval=1.25)
pyautogui.hotkey("ctrl", "n")
pyautogui.write("chrome://settings/system", interval=0.10)
pyautogui.press("enter", interval=1.25)

imageSecond = pyautogui.locateCenterOnScreen("chromebuttonsettings.PNG")
imageHardware = pyautogui.locateCenterOnScreen("chromebuttonsettingshardware.PNG")
reiniciar = pyautogui.locateCenterOnScreen("reiniciar.PNG")

pyautogui.moveTo(imageSecond)
pyautogui.click()
time.sleep(1)
pyautogui.moveTo(imageHardware)
pyautogui.click()
time.sleep(1)
pyautogui.moveTo(reiniciar)
pyautogui.click()

pyautogui.hotkey("win", interval=0.25)
pyautogui.write("powershell")
pyautogui.press("enter", interval=0.25)
pyautogui.write("taskkill /F /IM chrome.exe", interval=0.10)
pyautogui.press("enter", interval=0.25)
pyautogui.write("taskkill /F /IM firefox.exe", interval=0.10)
pyautogui.press("enter", interval=0.10)
pyautogui.write("taskkill /F /IM msedge.exe", interval=0.10)
pyautogui.press("enter", interval=0.10)
pyautogui.write("taskkill /F /IM Discord.exe")
pyautogui.press("enter", interval=0.10)
pyautogui.write("taskkill /F /IM Spotify.exe")
pyautogui.press("enter", interval=0.10)
pyautogui.write("taskkill /F /IM AnyDeskMSI.exe")
pyautogui.press("enter", interval=0.10)
pyautogui.write("taskkill /F /IM Teams.exe")
pyautogui.press("enter", interval=0.10)
pyautogui.write("cd Appdata")
pyautogui.press("enter", interval=0.10)
pyautogui.write("cd Local")
pyautogui.press("enter", interval=0.10)
pyautogui.write("cd Temp")
pyautogui.press("enter", interval=0.10)
pyautogui.write("del * -Force")
pyautogui.press("enter", interval=0.10)
pyautogui.write("A")
pyautogui.press("enter", interval=0.10)
pyautogui.write("cd ..")
pyautogui.press("enter", interval=0.10)
pyautogui.write("cd ..")
pyautogui.press("enter", interval=0.10)
pyautogui.write("cd ..")
pyautogui.press("enter", interval=0.10)
pyautogui.write("cd ..")
pyautogui.press("enter", interval=0.10)
pyautogui.write("cd ..")
pyautogui.press("enter", interval=0.10)
pyautogui.write("cd Windows")
pyautogui.press("enter", interval=0.10)
pyautogui.write("cd Temp")
pyautogui.press("enter", interval=0.10)
pyautogui.write("del * -Force")
pyautogui.press("enter", interval=0.10)
pyautogui.write("A")
pyautogui.press("enter", interval=0.10)

i = 0
while i <= 2:
    pyautogui.press("esc")
    i += 1
pyautogui.hotkey("win", "P", interval=0.25)
pyautogui.press("End")
pyautogui.press("Up")
pyautogui.press("enter", interval=1.25)
